title: Algorithmen
author:
  name: Jan Christiansen
  email: jan.christiansen@hs-flensburg.de
description: >
  Hochschule Flensburg / Fachbereich 3 Information und Kommunikation / Angewandte Informatik
exclude:
  - ignore/*.md

markdown: kramdown
remote_theme: jekyll/minima

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
    default_lang: java
